#! /bin/bash
set -e
set -x

# Populate the music_server directory with applications etc. from third-party sources.
# The system MUST be XOrg; Wayland is not supported.  Symptoms of Wayland include
# the ports for both :0 and :1 being occupied by the system, and VNC session apps 
# appearing in the system's GNOME session rather than in the VNC session.

# Versions to be downloaded and installed.
QUODLIBET_BRANCH=music-server-main
CAMILLADSP_RELEASE=v2.0.3
CAMILLAGUI_BACKEND_RELEASE=v2.1.1

# Some Ubuntu packages needed.
sudo apt install -y tigervnc-standalone-server openssh-server dbus-x11
sudo apt install -y git git-lfs gcc pkg-config python3-dev python3-pkgconfig python3-venv libcairo2-dev 
sudo apt install -y gobject-introspection libgirepository-2.0-dev
sudo apt install -y python3-gi gir1.2-gst-plugins-base-1.0 gir1.2-gst-plugins-bad-1.0
sudo apt install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-bad

# Pick up global environment definitions.
source env.sh

# Clean up any previous installations.
rm -rf "$PYTHON_ENVIRONMENT" "$QUOD_LIBET_DIR" "$CAMILLADSP_DIR"/bin "$CAMILLADSP_DIR"/camillagui-backend

# Place for log files.
mkdir -p $LOGS

# Create a Python virtual environment based on the current default Python. 
python3 -m venv "$PYTHON_ENVIRONMENT"

# Activate the virtual environment for this shell session
source "$PYTHON_ENVIRONMENT/bin/activate"

# Install Quod Libet from my private fork.
git clone https://github.com/jdykstra/quodlibet.git -b $QUODLIBET_BRANCH

# install Quod Libet dependencies.
# Poetry-plugin-export is needed for at least Jammy and later.
# Tell poetry not to use the system keyring;  we're not going to be
# accessing private repositories, and this eliminates a dependency.
# the requirements.txt file contains both packages with hash verification 
# and a Git URL (for camilladsp), and pip can't verify hashes for version control repositories.
export POETRY_KEYRING_BACKEND=keyring.backends.null.Keyring
pushd quodlibet
python3 -m pip install poetry poetry-plugin-export
poetry env use "$(which python3)"
poetry export --without-hashes > /tmp/requirements.txt
python3 -m pip install -r /tmp/requirements.txt
popd 

# Install the Camilladsp app from the official release.
mkdir -p "$CAMILLADSP_DIR"/bin 
wget -O /tmp/tarball.tgz https://github.com/HEnquist/camilladsp/releases/download/"$CAMILLADSP_RELEASE"/camilladsp-linux-amd64.tar.gz
tar -xzf /tmp/tarball.tgz -C "$CAMILLADSP_DIR/bin/"

# Install Camilladsp's GUI backend from the official release.
mkdir -p "$CAMILLADSP_DIR"/camillagui-backend 
wget -O /tmp/tarball.zip https://github.com/HEnquist/camillagui-backend/releases/download/"$CAMILLAGUI_BACKEND_RELEASE"/camillagui.zip
unzip /tmp/tarball.zip -d "$CAMILLADSP_DIR"/camillagui-backend/

# Copy pipewire configuration info needed for playing from bluetooth.
mkdir -p ~/.config/wireplumber/wireplumber.conf.d/
cp files_to_be_copied/51-bluetooth-custom.conf ~/.config/wireplumber/wireplumber.conf.d/

# Copy our custom config file for Camilladsp's GUI into its final directory.
# We do this because the config file contained in the GUI release 
# tarball uses relative pathnames.  Leave the original file in  place so 
# we don't accidentally remove it when updating the repository.
cp files_to_be_copied/jwd_camillagui.yml "$CAMILLADSP_DIR"/camillagui-backend/config/camillagui.yml

# Install camilladsp-backend's dependencies.
python3 -m pip install -r "$CAMILLADSP_DIR"/camillagui-backend/requirements.txt   

# We need serial access to the power controller.
sudo usermod -aG dialout "$USER"

# The snap version of Firefox does not work well without a real session,
# so use the conventional install directly from Mozilla.
# We need to specify a version because Ubuntu prioritizes the snap alternative.
sudo add-apt-repository ppa:mozillateam/ppa
sudo apt update
# Get the latest deb version of Firefox from the PPA (not the SNAP)
LATEST_FIREFOX_VERSION=$(apt-cache policy firefox | awk '/https:\/\/ppa.launchpadcontent.net\/mozillateam\/ppa/ {print v} {v=$1}' | head -n 1)
sudo apt install -y --allow-downgrades --allow-change-held-packages firefox="$LATEST_FIREFOX_VERSION"
sudo snap remove firefox
sudo apt-mark hold firefox

echo "**********  Install Completed Successfully  **********"
