#! /bin/bash
set -e
set -x

# Populate the music_server directory with applications etc. from third-party sources.
# python3-poetry must be installed.
# Some Ubuntu Jammy packages needed:  python3 python3.11-venv

# Versions to be downloaded and installed.
QUODLIBET_BRANCH=set_volume_from_peak
CAMILLADSP_RELEASE=v2.0.3
CAMILLAGUI_BACKEND_RELEASE=v2.1.1

# Pick up global environment definitions.
source env.sh

# Clean up any previous installations.
rm -rf "$PYTHON_ENVIRONMENT" quodlibet "$CAMILLADSP_DIR"/bin "$CAMILLADSP_DIR"/camillagui-backend

# Create a Python virtual environment based on the current default Python. 
python3 -m venv "$PYTHON_ENVIRONMENT"

# Install Quod Libet from my private fork.
git clone https://github.com/jdykstra/quodlibet.git -b $QUODLIBET_BRANCH

# install Quod Libet dependencies.
# ??  Jammy, Poetry version 1.1.12
pushd quodlibet
poetry env use ../"$PYTHON_ENVIRONMENT"/bin/python3
poetry export > /tmp/requirements.txt && "$PYTHON_ENVIRONMENT"/bin/python -m pip install -r /tmp/requirements.txt
popd 

# Install Camilladsp from the official release.
mkdir -p "$CAMILLADSP_DIR"/bin 
wget -O /tmp/tarball.tgz https://github.com/HEnquist/camilladsp/releases/download/"$CAMILLADSP_RELEASE"/camilladsp-linux-amd64.tar.gz
tar -xzf /tmp/tarball.tgz -C "$CAMILLADSP_DIR/bin/"

# Install Camilladsp's GUI backend from the official release.
mkdir -p "$CAMILLADSP_DIR"/camillagui-backend 
wget -O /tmp/tarball.zip https://github.com/HEnquist/camillagui-backend/releases/download/"$CAMILLAGUI_BACKEND_RELEASE"/camillagui.zip
unzip /tmp/tarball.zip -d "$CAMILLADSP_DIR"/camillagui-backend/

# Install camilladsp-backend's dependencies.
"$PYTHON_ENVIRONEMENT"/bin/python3 -m pip install -r "$CAMILLADSP_DIR"/camillagui-backend/requirements.txt   

echo "**********  Setup Completed  **********"
