#! /bin/bash
set -e
set -x

# Populate the music_server directory with applications etc. from third-party sources.
# Some Ubuntu Jammy packages needed:  python3 python3.11-venv libgirepository1.0-dev.

# Versions to be downloaded and installed.
QUODLIBET_BRANCH=set_volume_from_peak
CAMILLADSP_RELEASE=v2.0.3
CAMILLAGUI_BACKEND_RELEASE=v2.1.1

# Pick up global environment definitions.
source env.sh

# Clean up any previous installations.
rm -rf "$PYTHON_ENVIRONMENT" "$QUOD_LIBET_DIR" "$CAMILLADSP_DIR"/bin "$CAMILLADSP_DIR"/camillagui-backend

# Place for log files.
mkdir -p $LOGS

# Create a Python virtual environment based on the current default Python. 
python3 -m venv "$PYTHON_ENVIRONMENT"

# Install Quod Libet from my private fork.
git clone https://github.com/jdykstra/quodlibet.git -b $QUODLIBET_BRANCH

# install Quod Libet dependencies.
# Poetry-plugin-export is needed for at least Jammy and later.
pushd quodlibet
"$PYTHON" -m pip install poetry poetry-plugin-export
"$PYTHON" -m poetry env use "$PYTHON_ENVIRONMENT"/bin/python3
"$PYTHON" -m poetry export > /tmp/requirements.txt
"$PYTHON" -m pip install -r /tmp/requirements.txt
popd 

# Install Camilladsp from the official release.
mkdir -p "$CAMILLADSP_DIR"/bin 
wget -O /tmp/tarball.tgz https://github.com/HEnquist/camilladsp/releases/download/"$CAMILLADSP_RELEASE"/camilladsp-linux-amd64.tar.gz
tar -xzf /tmp/tarball.tgz -C "$CAMILLADSP_DIR/bin/"

# Install Camilladsp's GUI backend from the official release.
mkdir -p "$CAMILLADSP_DIR"/camillagui-backend 
wget -O /tmp/tarball.zip https://github.com/HEnquist/camillagui-backend/releases/download/"$CAMILLAGUI_BACKEND_RELEASE"/camillagui.zip
unzip /tmp/tarball.zip -d "$CAMILLADSP_DIR"/camillagui-backend/

# Install camilladsp-backend's dependencies.
"$PYTHON" -m pip install -r "$CAMILLADSP_DIR"/camillagui-backend/requirements.txt   

echo "**********  Setup Completed  **********"
