#! /bin/bash
set -e

# This script is executed by the VNC server when its session is created.
# ~/.vnc/xstartup points to it.

source env.sh

# Start infrared remote control daemon.
irexec &

# Start Quod Libet music player.
$PYTHON $QUOD_LIBET_DIR/quodlibet.py > $LOGS/quodlibet.log   &

# Start camilladsp.  It will error out if there is nothing connected to the input side
# of the ALSA loopback device, so delay a while to give quod libet time to finish
# starting up. 
sleep 10
$CAMILLADSP_DIR/bin/camilladsp -w -p1234 -s $CAMILLADSP_DIR/statefile.yaml -l debug -o $LOGS/camilladsp.log $CAMILLADSP/configs/default_config.yaml &

# Start the backend for the camiliadsp GUI.
$CAMILLADSP_DIR/camillagui_venv/bin/python $CAMILLADSP_DIR/gui/main.py > $LOGS/gui_backend.log  &

# Start a terminal window.  The VNC server will exit when this process does.
xterm

