#!/bin/sh

# Uncomment the following two lines for normal desktop:
#  unset SESSION_MANAGER
#  exec /etc/X11/xinit/xinitrc

# Create an .Xauthority file unique to this VNC session.
echo "Hello"
#filename="vnc_$(date +%s).Xauthority"
#export XAUTHORITY="$HOME/.$filename"
#touch $XAUTHORITY
#chmod 600 $XAUTHORITY
#xauth generate $DISPLAY $XAUTHORITY
#echo "XAUTHORITY file is " $XAUTHORITY

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
#  x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &
/home/jwd/music_server/start_everything_else
