title: "Subwoofer crossover with 10/22 mains and sub filters"
description: >
  Mains:  10/30 minimum Phase FIR, processed using "important note" method and not 
  incorrectly adding in the crossover correction.
  Currently just using the L filter.
  Sub:  Impulse response from 10/8 speaker measurements and 10/22 filter creation.

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # ALSA device constructed by compositing Benchmark DAC - Channels 0 and 1
    # and Dell Latitude integrated audio - Channels 2 and 3
    type: Alsa
    channels: 4
    device: "composite_dac"
    format: S32LE
    
mixers:
  mono:
    channels:
      in: 2
      out: 3
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2                 # Output to channel 2
        sources:
          - channel: 0          # Input from channels 0 and 1
            gain: 6
          - channel: 1       
            gain: 6               
  
  invert:
    channels:
      in: 3
      out: 4
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 6
      - dest: 1
        sources:
          - channel: 1
            gain: 6
      - dest: 2
        sources:
          - channel: 2
            gain: 0
      - dest: 3                 # Output to channel 3
        sources:
          - channel: 2          # Input from channel 2
            gain: 0
            inverted: true               

filters:
  infrasonic:
    parameters:
      freq:  20
      type:  HighpassFO
    type: Biquad

# Highpass / Lowpass 2nd order (from camilladsp example "all filters")
# Note that the hardware filter in the subwoofer is 1st order, which 
# would be a Q of 0.5 (I think).
  highpass:
    type: Biquad
    parameters:
      type: Highpass
      freq: 100
      q: 1.0

  lowpass:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 100
      q: 1.0

  l_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  r_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  sub_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-22_sub_amplitude_impulse_B.wav

# Delay the sub signal to compensate for the FIR filter on the mains.
  sub_delay:
    type: Delay
    parameters:
      delay: 170       # Ballpark by ear
      unit: ms
      subsample: false

# ?? The infrasonic filter affects phase.  For simplicity and performance,
# ?? it should probably be made part of the lowpass filter.
pipeline:
  - type: Mixer
    description: "Mix input channels 0 and 1 to new mono channel 2"
    name: mono
    
  - type: Filter
    channel: 0
    names:
    - l_fir

  - type: Filter
    channel: 1
    names:
    - r_fir

  - type: Filter
    channel: 2
    names:
    - sub_fir

  - type: Mixer
    description: "Invert mono channel 2 to channel 3 for balanced output"
    name: invert


