title: "44.1 KHz Filter"
description: >
  Mains:  10/30 minimum Phase FIR, processed using "important note" method and not 
  incorrectly adding in the crossover correction.
  Currently just using the L filter.
  Sub:  Impulse response from 10/8 speaker measurements and 10/22 filter creation.

devices:
  capture_samplerate: 44100
  samplerate: 44100
  enable_rate_adjust: true
  chunksize: 8192
  # Increase target level to avoid underruns.  Current value is 
  # max alllowed;  it probably could be less.
  target_level: 16383

  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # RME Digiface USB.  Channels 0 and 1 are mains, 2 and 3 are sub.  
    # The Digiface USB supports different sample rates depending on how many inputs
    # and outputs are in use.  The current (2024) Linux sound drivers only allow
    # 44.1 KHz to be selected if all 34 channels are in use.  We output silence to
    # the unused channels.
    type: Alsa
    channels: 34
    device: "hw:USB24240187,0"
    format: S32LE
    
mixers:
  mono:
    channels:
      in: 2
      out: 3
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2                 # Output to channel 2
        sources:
          - channel: 0          # Input from channels 0 and 1
            gain: -18
          - channel: 1       
            gain: -18           
  
  #  Output silence to all unused output channels.  See comment in devices specification.
  fanout:
    channels:
      in: 3
      out: 34
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2
        sources:
          - channel: 2
            gain: 0
      - dest: 3   
        sources:
          - channel: 2 
            gain: -100
      - dest: 4  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 5  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 6  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 7  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 8  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 9  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 10  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 11  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 12  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 13  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 14  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 15  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 16  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 17  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 18  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 19  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 20  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 21  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 22  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 23  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 24  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 25  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 26  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 27  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 28  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 29  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 30  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 31  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 32  # Not used
        sources:
          - channel: 2
            gain: -100
      - dest: 33  # Not used
        sources:
          - channel: 2
            gain: -100
          
filters:
  l_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  r_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  sub_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-22_sub_amplitude_impulse_B.wav

# Delay the sub signal to compensate for the FIR filter on the mains.
  sub_delay:
    type: Delay
    parameters:
      delay: 0       # Ballpark by ear
      unit: ms
      subsample: false

pipeline:
  - type: Mixer
    description: "Mix input channels 0 and 1 to new mono channel 2"
    name: mono
    
  - type: Filter
    channel: 0
    names:
    - l_fir

  - type: Filter
    channel: 1
    names:
    - r_fir

  - type: Filter
    channel: 2
    names:
    - sub_fir

  - type: Mixer
    description: "Fan out to all 34 channels"
    name: fanout