title: "Minimum Phase 9-11 Two Channel"
description: >
  Measurements 9-10, from listening position without sub.
  Filters generated per cannonical process, modified to delete crossover filters
  when nulling out phase shifts.
  Infrasonic filter is a 20 Hz highpass.

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Write to the default subdevice of the Benchmark DAC
    type: Alsa
    channels: 2
    device: "hw:B20,0"
    format: S32LE

filters:
  infrasonic:
    parameters:
      freq:  20
      type:  HighpassFO
    type: Biquad

  fir_l:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/9-11_L_minimum_phase.wav

  fir_r:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/9-11_R_minimum_phase.wav

pipeline:
  - type: Filter
    channel: 0
    names:
    - infrasonic
    - fir_l

  - type: Filter
    channel: 1
    names:
    - infrasonic
    - fir_r
