title: "For current-ubuntu VM image"
description: >
  Basic configuration for current-ubuntu VM image

devices:
  capture_samplerate: 44100
  samplerate: 48000
  chunksize: 8192
  resampler:
    type: Synchronous
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Virtualized audio 
    type: Alsa
    channels: 2
    device: "hw:I82801AAICH,0"
    format: S16LE

pipeline:
 
