title: "Default"
description: >
  Sub:  Impulse response from 10/8 speaker measurements and 10/22 filter creation.
  Recomputed 12/19/2024 for 176.4 KHz sample rate.

devices:
  capture_samplerate: 44100
  # High sample rate to allow for high quality filtering.
  # Current value is 4*capture_samplerate.
  samplerate: 176400
  enable_rate_adjust: true
  chunksize: 8192
  # Increase target level to avoid underruns.  Current value is 
  # max alllowed;  it probably could be less.
  target_level: 16383
  resampler:
    type: Synchronous
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # RME Digiface USB.  Channels 0 and 1 are mains, 2 and 3 are sub.  
    # The Digiface USB supports different sample rates depending on how many inputs
    # and outputs are in use.  The current (2024) Linux sound drivers only allow
    # 44.1 KHz to be selected if all 34 channels are in use.  We output silence to
    # the unused channels.
    type: Alsa
    channels: 10
    device: "hw:USB24240187,0"
    format: S32LE
    
mixers:

  # Generate a new mono channel for the sub from the left and right channels.
  # Also tweak the L/R balance to compensate for room effects.
  mono:
    channels:
      in: 2
      out: 3
    mapping:
      - dest: 0               # Left channel
        sources:
          - channel: 0
            gain: 0
      - dest: 1               # Right channel
        sources:
          - channel: 1
            gain: 0
      - dest: 2               # New mono channel for sub
        sources:
          - channel: 0        
            gain: -6          # Compensate for summing
          - channel: 1       
            gain: -6           
  
  #  Output silence to all unused output channels.  See comment in devices specification.
  fanout:
    channels:
      in: 3
      out: 10
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2
        sources:
          - channel: 2
            gain: 0
      - dest: 3    # Not used
        mute: true
        sources:
          - channel: 2 
            gain: 0
      - dest: 4  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0
      - dest: 5  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0
      - dest: 6  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0
      - dest: 7  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0
      - dest: 8  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0
      - dest: 9  # Not used
        mute: true
        sources:
          - channel: 2
            gain: 0

filters:
  sub_fir_compensation:
    type: Delay
    parameters:
      delay: 92.925
      unit: ms
      subsample: false
      
  sub_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/12-19-sub_amplitude_impulse.wav

  sub_dsp_compensation:
    type: Delay
    parameters:
      delay: 27
      unit: ms
      subsample: false

  FS_limiter:
    type: Limiter
    parameters:
      soft_clip: false
      clip_limit: -1.0

pipeline:
  - type: Mixer
    description: "Mix input channels 0 and 1 to new mono channel 2"
    name: mono
    
  - type: Filter
    channel: 0
    names:
    - sub_dsp_compensation 
    - sub_fir_compensation
    - FS_limiter

  - type: Filter
    channel: 1
    names:
    - sub_dsp_compensation
    - sub_fir_compensation
    - FS_limiter

  - type: Filter
    channel: 2
    names:
    - sub_fir
    - FS_limiter

  - type: Mixer
    description: "Fan out to all channels"
    name: fanout
