title: "Subwoofer crossover with 10/22 mains and sub filters"
description: >
  Mains:  10/30 minimum Phase FIR, processed using "important note" method and not 
  incorrectly adding in the crossover correction.
  Currently just using the L filter.
  Sub:  Impulse response from 10/8 speaker measurements and 10/22 filter creation.

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # RME Digiface USB.  Channels 0 and 1 are mains, 2 and 3 are sub.  Remaining channels are unused.
    type: Alsa
    channels: 10
    device: "hw:USB24192396,0"
    format: S32LE
    
mixers:
  mono:
    channels:
      in: 2
      out: 3
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2                 # Output to channel 2
        sources:
          - channel: 0          # Input from channels 0 and 1
            gain: -18
          - channel: 1       
            gain: -18           
  
  duplicate:
    channels:
      in: 3
      out: 10
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
      - dest: 1
        sources:
          - channel: 1
            gain: 0
      - dest: 2
        sources:
          - channel: 2
            gain: 0
      - dest: 3   
        sources:
          - channel: 2 
            gain: 0
      - dest: 4  # Not used
        sources:
          - channel: 2
            gain: 0
      - dest: 5  # Not used
        sources:
          - channel: 2
            gain: 0
      - dest: 6  # Not used
        sources:
          - channel: 2
            gain: 0
      - dest: 7  # Not used
        sources:
          - channel: 2
            gain: 0
      - dest: 8  # Not used
        sources:
          - channel: 2
            gain: 0
      - dest: 9  # Not used
        sources:
          - channel: 2
            gain: 0
            

filters:
  l_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  r_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-30_L_minimum_impulse.wav

  sub_fir:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/10-22_sub_amplitude_impulse_B.wav

# Delay the sub signal to compensate for the FIR filter on the mains.
  sub_delay:
    type: Delay
    parameters:
      delay: 0       # Ballpark by ear
      unit: ms
      subsample: false

pipeline:
  - type: Mixer
    description: "Mix input channels 0 and 1 to new mono channel 2"
    name: mono
    
  - type: Filter
    channel: 0
    names:
    - l_fir

  - type: Filter
    channel: 1
    names:
    - r_fir

  - type: Filter
    channel: 2
    names:
    - sub_fir

  - type: Mixer
    description: "Duplicate mono channel 2 to channel 3"
    name: duplicate