title: "Default Configuration"
description: "Filters from 6-12-24 measurements without sub. Sample rate mismatch.  Individual left and right, no manual tweaking"

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Write to the default subdevice of the Benchmark DAC
    type: Alsa
    channels: 2
    device: "hw:B20,0"
    format: S32LE

filters:
  7-5-24_6-12_L_no_sub_1:
    parameters:
      freq: 132.5
      gain: 4.8
      q: 5.451
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_2:
    parameters:
      freq: 139.0
      gain: -6.9
      q: 4.995
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_3:
    parameters:
      freq: 214.0
      gain: -7.3
      q: 4.951
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_4:
    parameters:
      freq: 215.0
      gain: 4.2
      q: 2.277
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_5:
    parameters:
      freq: 393.0
      gain: 5.1
      q: 5.706
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_6:
    parameters:
      freq: 420.0
      gain: -9.3
      q: 4.725
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_7:
    parameters:
      freq: 443.0
      gain: 5.2
      q: 6.256
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_8:
    parameters:
      freq: 671.0
      gain: -3.8
      q: 4.93
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_9:
    parameters:
      freq: 760.0
      gain: -1.8
      q: 4.957
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_10:
    parameters:
      freq: 931.0
      gain: -2.0
      q: 4.969
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_11:
    parameters:
      freq: 1144.0
      gain: -14.1
      q: 4.999
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_12:
    parameters:
      freq: 1227.0
      gain: 11.4
      q: 3.235
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_13:
    parameters:
      freq: 1347.0
      gain: -9.0
      q: 4.986
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_14:
    parameters:
      freq: 1587.0
      gain: -3.0
      q: 4.973
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_15:
    parameters:
      freq: 1907.0
      gain: 10.0
      q: 3.698
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_16:
    parameters:
      freq: 1948.0
      gain: -11.4
      q: 4.984
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_17:
    parameters:
      freq: 6272.0
      gain: 1.5
      q: 3.87
      type: Peaking
    type: Biquad
  7-5-24_6-12_L_no_sub_18:
    parameters:
      freq: 6684.0
      gain: -3.2
      q: 4.908
      type: Peaking
    type: Biquad

  7-5-24_6-12_R_no_sub_1:
      parameters:
        freq: 128.5
        gain: 2.7
        q: 6.8
        type: Peaking
      type: Biquad
  7-5-24_6-12_R_no_sub_2:
    parameters:
      freq: 152.5
      gain: -12.4
      q: 4.324
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_3:
    parameters:
      freq: 160.5
      gain: 8.7
      q: 4.378
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_4:
    parameters:
      freq: 245.0
      gain: 1.5
      q: 4.409
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_5:
    parameters:
      freq: 270.0
      gain: -3.4
      q: 4.781
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_6:
    parameters:
      freq: 400.0
      gain: 6.5
      q: 4.87
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_7:
    parameters:
      freq: 412.0
      gain: -12.2
      q: 4.999
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_8:
    parameters:
      freq: 482.0
      gain: 5.5
      q: 1.549
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_9:
    parameters:
      freq: 527.0
      gain: 7.4
      q: 7.346
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_10:
    parameters:
      freq: 541.0
      gain: -10.5
      q: 4.962
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_11:
    parameters:
      freq: 660.0
      gain: -6.3
      q: 3.634
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_12:
    parameters:
      freq: 919.0
      gain: 0.2
      q: 3.626
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_13:
    parameters:
      freq: 1064.0
      gain: -5.4
      q: 3.351
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_14:
    parameters:
      freq: 1392.0
      gain: -10.0
      q: 4.999
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_15:
    parameters:
      freq: 1452.0
      gain: 6.7
      q: 5.799
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_16:
    parameters:
      freq: 2049.0
      gain: -5.9
      q: 4.992
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_17:
    parameters:
      freq: 2118.0
      gain: 4.7
      q: 7.409
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_18:
    parameters:
      freq: 2504.0
      gain: 1.6
      q: 1.758
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_19:
    parameters:
      freq: 4650.0
      gain: 2.8
      q: 3.926
      type: Peaking
    type: Biquad
  7-5-24_6-12_R_no_sub_20:
    parameters:
      freq: 5482.0
      gain: -3.8
      q: 1.034
      type: Peaking
    type: Biquad

pipeline:
  - type: Filter
    channel: 0
    names:
    - 7-5-24_6-12_L_no_sub_1
    - 7-5-24_6-12_L_no_sub_2
    - 7-5-24_6-12_L_no_sub_3
    - 7-5-24_6-12_L_no_sub_4
    - 7-5-24_6-12_L_no_sub_5
    - 7-5-24_6-12_L_no_sub_6
    - 7-5-24_6-12_L_no_sub_7
    - 7-5-24_6-12_L_no_sub_8
    - 7-5-24_6-12_L_no_sub_9
    - 7-5-24_6-12_L_no_sub_10
    - 7-5-24_6-12_L_no_sub_11
    - 7-5-24_6-12_L_no_sub_12
    - 7-5-24_6-12_L_no_sub_13
    - 7-5-24_6-12_L_no_sub_14
    - 7-5-24_6-12_L_no_sub_15
    - 7-5-24_6-12_L_no_sub_16
    - 7-5-24_6-12_L_no_sub_17
    - 7-5-24_6-12_L_no_sub_18

  - type: Filter
    channel: 1
    names:
    - 7-5-24_6-12_R_no_sub_1
    - 7-5-24_6-12_R_no_sub_2
    - 7-5-24_6-12_R_no_sub_3
    - 7-5-24_6-12_R_no_sub_4
    - 7-5-24_6-12_R_no_sub_5
    - 7-5-24_6-12_R_no_sub_6
    - 7-5-24_6-12_R_no_sub_7
    - 7-5-24_6-12_R_no_sub_8
    - 7-5-24_6-12_R_no_sub_9
    - 7-5-24_6-12_R_no_sub_10
    - 7-5-24_6-12_R_no_sub_11
    - 7-5-24_6-12_R_no_sub_12
    - 7-5-24_6-12_R_no_sub_13
    - 7-5-24_6-12_R_no_sub_14
    - 7-5-24_6-12_R_no_sub_15
    - 7-5-24_6-12_R_no_sub_16
    - 7-5-24_6-12_R_no_sub_17
    - 7-5-24_6-12_R_no_sub_18
    - 7-5-24_6-12_R_no_sub_19
    - 7-5-24_6-12_R_no_sub_20
