title: "FIR"
description: "FIR filter from both."

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Write to the default subdevice of the Benchmark DAC
    type: Alsa
    channels: 2
    device: "hw:B20,0"
    format: S32LE

filters:
  infrasonic:
    parameters:
      freq:  20
      type:  HighpassFO
    type: Biquad

  fir_left:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/2800_impulse_7-15.wav
  fir_right:
    type: Conv
    parameters:
      type: Wav
      filename: /home/jwd/music_server/camilladsp/coeffs/2801_impulse_7-15.wav

pipeline:
  - type: Filter
    channel: 0
    names:
    - infrasonic
    - fir_left

  - type: Filter
    channel: 1
    names:
    - infrasonic
    - fir_right
