title: "Subwoofer crossover WIP"
description: "Initially based on stepbystep.md in the camilladsp repo."

devices:
  samplerate: 44100
  chunksize: 2048
  capture_samplerate: 44100
  enable_rate_adjust: true
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Benchmark DAC - Channels 0 and 1
    type: Alsa
    channels: 2
    device: "hw:B20,0"
    format: S32LE
    # Dell Latitude integrated audio - Channels 2 and 3
    type: Alsa
    channels: 2
    device: "hw:1,0"

    
mixers:
  mono:
    mapping:
      - dest: 2                 <---- Output to channel 2
        sources:
          - channel: 0          <---- Input from channels 0 and 1
            gain: -6
            channel: 1       
          - gain: -6               
    channels:
      in: 2
      out: 1
  
  invert:
    mapping:
      - dest: 3                 <---- Output to channel 3
        sources:
          - channel: 2          <---- Input from channel 2
            invert: true               
    channels:
      in: 1
      out: 1

  to4chan:
    description: "NOT USED:  Expand 2 channels to 4.  Channel 0 duplicated to channel 2, 1 duplicated to channel 3."
    channels:
      in: 2
      out: 4
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 2      <---- new!
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 3      <---- new!
        sources:
          - channel: 1
            gain: 0
            inverted: false

filters:
  infrasonic:
    parameters:
      freq:  20
      type:  HighpassFO
    type: Biquad

# Highpass / Lowpass 2nd order (from camilladsp example "all filters")
  highpass:
    type: Biquad
    parameters:
      type: Highpass
      freq: 100
      q: 1.0

  lowpass:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 100
      q: 1.0

# ?? The infrasonic filter affects phase.  For simplicity and performance,
# ?? it should probably be made part of the lowpass filter.
pipeline:
  - type: Mixer
    description: "Mix input channels 0 and 1 to new mono channel 2"
    name: mono

  - type: Filter
    channel: 0
    names:
    - highpass

  - type: Filter
    channel: 1
    names:
    - highpass

  - type: Filter
    channel: 2
    names:
    - infrasonic
    - lowpass

  - type: Mixer
    description: "Invert mono channel 2 to channel 3 for balanced output"
    name: invert


