title: "Basic configuration for ubuntu-current VM image"
description: >
  Basic configuration for ubuntu-current VM image

devices:
  capture_samplerate: 44100
  # High sample rate to allow for high quality filtering.
  # Current value is 4*capture_samplerate.
  samplerate: 176400
  enable_rate_adjust: true
  chunksize: 8192
  # Increase target level to avoid underruns.  Current value is 
  # max alllowed;  it probably could be less.
  target_level: 16383
  resampler:
    type: Synchronous
  capture:
    # Read from the default subdevice of the ALSA loopback device.
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S16LE
  playback:
    # Virtualized audio 
    type: Alsa
    channels: 2
    device: "hw:Intel 82801AA-ICH,0"
    format: S32LE

pipeline:
 
